### ISSUE TITLE
Add option to run command to get config(?)

### ISSUE THREAD

**Issue by kvz** [yinheli/sshw#11]
Our platform is highly volatile and it would be cool if we could pass the path to a script, that would be executed to output the current fleet config.

**Comment by yinheli** [comment]
Could you please show some examples?

**Comment by kvz** [comment]
Like, if I could point to a bash script which is executable, sshw could detect this and execute it to get a list of servers (instead of reading the contents of the file). My script would then fetch a list of current servers, and output the config dynamically.
