### ISSUE TITLE
Use `~/.ssh/config`

### ISSUE THREAD

**Issue by lardissone** [yinheli/sshw#12]
Would be great if it uses SSH config file instead of a custom one.

So we can reuse hosts with different apps without having duplicated configurations, for example git: `git clone ssh://gitserver/repo.git`.

**Comment by yinheli** [comment]
Good idea.

**Comment by CompileNix** [comment]
I recommend for reopening this issue.
@yinheli do you want to do this?

**Comment by yinheli** [comment]
@compilenix Okay, But I don't have time to do this feature.

**Comment by CompileNix** [comment]
Thanks :-)
