### ISSUE TITLE
Select the server based on the number

### ISSUE THREAD

**Issue by jinhai-cloud** [yinheli/sshw#16]
Each server corresponds to a number, and the corresponding server can be selected according to the number

**Comment by jinhai-cloud** [comment]
Like：https://github.com/islenbo/autossh

**Comment by yinheli** [comment]
This tool use `github.com/manifoldco/promptui` to select host, the promptui lib, which not support number selection yet.

But you can press `/` key to toggle search mode. It is also very fast way to find which host to connect, even you  have big host list.
