### ISSUE TITLE
Feature idea: dinamic hosts from cloud metadata

### ISSUE THREAD

**Issue by eduardohki** [yinheli/sshw#31]
Hello!

First, thanks for this amazing idea! It is really useful to remove overhead over SSH connection management!

I have a feature idea: I think there are lots of people that have the need of managing cloud instances (EC2, GCE, AzureVMs) which change constantly due to a dynamic environment.

Because of this, it may be a bit challenging to manage the static configuration files on every change, and also spread it accordingly across the team.

So my idea would be to have support to add dynamic hosts based on Cloud host metadata, e.g. get the Name, login user and internal or public IP of a specific host on EC2, and then be able to select them (using ssh keys or even asking for password if none).

Do you think it's something you think that this tool could benefit from? I would love to help with this, however I have zero experience with Go (but would be happy to learn by doing it).

Cheers,
Eduardo

**Comment by yinheli** [comment]
I' don't have cloud servers which you mentioned above.

Maybe this feature can be implemented:
add a sub-command to fetch cloud servers and merge local configuration.
