### ISSUE TITLE
[Question]: is there a way to have password encrypted in .sshw

### ISSUE THREAD

**Issue by sasadangelo** [yinheli/sshw#47]
Hi,

I would like to know if there is a way to have a password encrypted in the .sshw file so that they are not exposed to attackers.
How can I do it?
Thx

**Comment by yinheli** [comment]
Not yet, maybe you should try ssh key instead

**Comment by sasadangelo** [comment]
Ok thank you, I'll try to do it by myself. Any suggestions on the type of change I have to do?
