### ISSUE TITLE
sshw disconnect automatically

### ISSUE THREAD

**Issue by world520ai** [yinheli/sshw#58]
when I comment below, everything is ok.
//go func() {
	//	for {
	//		time.Sleep(time.Second * 10)
	//		client.SendRequest("keepalive@openssh.com", false, nil)
	//	}
	//}()

**Comment by yinheli** [comment]
This use to implements keepalive features.

reference: 
- https://datatracker.ietf.org/doc/draft-ietf-netconf-server-model/06/
- https://www.rfc-editor.org/rfc/rfc8071.txt
- https://gitlab.com/gitlab-org/gitlab-shell/-/merge_requests/622

bug needs to investigate.

**Comment by world520ai** [comment]
I agree with you, but if client.SendRequest("[keepalive@openssh.com](mailto:keepalive@openssh.com)", false, nil) could cause the connection terminated? I think this is possible.

![image](https://user-images.githubusercontent.com/4435013/189266618-57cf4164-457d-4683-80ee-5db0e2cd1e64.png)
