### ISSUE TITLE
Problem using SSH Keys

### ISSUE THREAD

**Issue by virtuallytd** [yinheli/sshw#8]
There is a problem when using SSH Keys, it looks like its not able to read the key for some reason or use the stored ssh agent.

```
[sshw] 2018/07/24 11:44:01 [error] ssh: handshake failed: ssh: unable to authenticate, attempted methods [none], no supported methods remain
```

**Comment by yinheli** [comment]
sshw default use the private key located at `~/.ssh/id_rsa`

**Comment by virtuallytd** [comment]
If it's not in the default location does it not work? As I have multiple keys used on different servers.

**Comment by yinheli** [comment]
@virtuallytd now support custom key path #2, please download the new version.
